name: Lint Script and Style
description: Lint JavaScript, Sass and CSS files

inputs:
  script-paths:
    required: false
    default: .
    description: Paths to the directories where the package.json files are located.

runs:
  using: composite
  steps:
    - name: Setup NodeJs Extensions
      shell: pwsh
      run: |
        Write-Output $PWD.Path
        tree

        Write-Output '${{ github.action_path }}'
        tree '${{ github.action_path }}'

        $LombiqNodeJsExtensions = $(Resolve-Path '${{ github.action_path }}/../../../Lombiq.NodeJs.Extensions').Path
        Write-Output "LOMBIQ_NODEJS_EXTENSIONS=$LombiqNodeJsExtensions"
        "LOMBIQ_NODEJS_EXTENSIONS=$LombiqNodeJsExtensions" >> $Env:GITHUB_ENV

        cd $LombiqNodeJsExtensions
        pnpm install --prefer-offline
        pnpm link --global

    - name: Execute Linting
      shell: pwsh
      run: |
        $project = Get-Content $Env:LOMBIQ_NODEJS_EXTENSIONS/package.json | ConvertFrom-Json -AsHashtable
        $packages = $project['devDependencies'].Keys | ForEach-Object { $version = $project['devDependencies'][$PsItem]; "$PsItem@$version" }

        function Test-NoPath($Paths) { -not (Test-Path -Path $Paths | Where-Object { $PsItem }) }

        function Invoke-NodeJsExtensions($Type) { npm explore nodejs-extensions -- pnpm "lint:$Type" }

        function Install-NodeJsExtensions($Path)
        {
          Set-Location $Path

          if (Test-NoPath -Paths package.json,package.json5,package.yaml) {
            Copy-Item $Env:LOMBIQ_NODEJS_EXTENSIONS/config/consumer/package.project.json package.json
          }

          if (Test-NoPath -Paths .eslintrc,.eslintrc.js) {
            Copy-Item $Env:LOMBIQ_NODEJS_EXTENSIONS/config/consumer/.eslintrc.project.js .eslintrc.js
          }

          pnpm link --global nodejs-extensions
          pnpm install @packages
        }

        Get-Item ${{ inputs.script-paths }} | ForEach-Object {
          Install-NodeJsExtensions -Path $PsItem
          Invoke-NodeJsExtensions -Type scripts
        }