<Project>

  <!-- We're using Items to find the absolute path to the DLL file, because it's nested a few levels deep. The DLL is
       located either underneath the \bin folder (using the source), or the \lib folder (using the NuGet package). -->
  <PropertyGroup>
    <BuildTasksRoot>$(MSBuildThisFileDirectory)</BuildTasksRoot>
    <BuildTasksProjectFile>$(BuildTasksRoot)/Lombiq.NodeJs.Extensions.BuildTasks.csproj</BuildTasksProjectFile>
    <BuildTasksAssemblyName>Lombiq.NodeJs.Extensions.BuildTasks.dll</BuildTasksAssemblyName>
    <!-- We check for \lib here because that folder will always exist in the NuGet package and never in source. In
         contrast, the \bin folder does not exist after a Clean operation, so checking for \bin would fail in early
         build stages. -->
    <BuildTasksAssemblyPath
      Condition="!Exists('$(BuildTasksRoot)/lib')">$(BuildTasksRoot)/bin/$(Configuration)/netstandard2.0/$(BuildTasksAssemblyName)</BuildTasksAssemblyPath>
    <BuildTasksAssemblyPath
      Condition="Exists('$(BuildTasksRoot)/lib')">$(BuildTasksRoot)/lib/netstandard2.0/$(BuildTasksAssemblyName)</BuildTasksAssemblyPath>
  </PropertyGroup>

  <!--<Target Name="EnsureTaskAssemblyBuilt" BeforeTargets="Compile" Condition="Exists('$(BuildTasksProjectFile)')">
    <Exec Command="echo happening $(BuildTasksProjectFile)" />
    <MSBuild Projects="$(BuildTasksProjectFile)" Targets="Build" />
  </Target>-->

  <!-- Setting TaskFactory="TaskHostFactory" will span a new task for every invocation, which is what we want. Also, the
       AssemblyFile attribute will only be resolved when the Task is actually called. -->
  <UsingTask AssemblyFile="$(BuildTasksAssemblyPath)" TaskName="ExecWithMutex" TaskFactory="TaskHostFactory" />

  <Target Name="TestEcho" BeforeTargets="EnablePnpm">
    <ExecWithMutex
      Command="echo Before EnablePnpm from BuildTasks"
      MutexName="EnablePnpm"
      Access="Exclusive"
      TimeoutSeconds="$(MutexWaitTimeoutSeconds)"
      IgnoreStandardErrorWarningFormat="true"
      StandardOutputImportance="high" />
  </Target>

</Project>
