name: Lint Script and Style
description: Lint JavaScript, Sass and CSS files

inputs:
  script-paths:
    required: false
    default: .
    description: Paths for JavaScript linting to the directories where the package.json files are located.
  style-paths:
    required: false
    default: .
    description: Paths for Sass linting to the directories where the package.json files are located.
  style-css-paths:
    required: false
    default: .
    description: Paths for CSS linting to the directories where the package.json files are located.

runs:
  using: composite
  steps:
    - name: Setup NodeJs Extensions
      shell: pwsh
      run: |
        '${{ github.action_path }}' >> $Env:GITHUB_PATH

        $LombiqNodeJsExtensions = $(Resolve-Path '${{ github.action_path }}/../../../Lombiq.NodeJs.Extensions').Path
        Write-Output "LOMBIQ_NODEJS_EXTENSIONS=$LombiqNodeJsExtensions"
        "LOMBIQ_NODEJS_EXTENSIONS=$LombiqNodeJsExtensions" >> $Env:GITHUB_ENV
        "LOMBIQ_NODEJS_EXTENSIONS_WARN_AS_ERROR=true" >> $Env:GITHUB_ENV

        corepack enable
        corepack prepare pnpm@8.15.9+sha1.aa4bc353b5f59fe1f1df5d802ce049ddf7f3c60e --activate

        cd $LombiqNodeJsExtensions
        pnpm install --prefer-offline --no-frozen-lockfile
        pnpm link --global

    - name: Execute Linting
      shell: pwsh
      run: |
        $library = $Env:LOMBIQ_NODEJS_EXTENSIONS
        $project = Get-Content $library/package.json | ConvertFrom-Json -AsHashtable
        $packages = $project['devDependencies'].Keys | ForEach-Object { $version = $project['devDependencies'][$PsItem]; "$PsItem@$version" }

        Invoke-NodeJsLinter -Packages $packages -LibraryPath $library -Type scripts -Paths '${{ inputs.script-paths }}'
        Invoke-NodeJsLinter -Packages $packages -LibraryPath $library -Type styles -Paths '${{ inputs.style-paths }}'
        Invoke-NodeJsLinter -Packages $packages -LibraryPath $library -Type styles-css -Paths '${{ inputs.style-css-paths }}'
