name: Lint Script and Style
description: Lint JavaScript, Sass and CSS files

inputs:
  script-paths:
    required: false
    default: .
    description: Paths for JavaScript linting to the directories where the package.json files are located.
  style-paths:
    required: false
    default: .
    description: Paths for Sass linting to the directories where the package.json files are located.
  style-css-paths:
    required: false
    default: .
    description: Paths for CSS linting to the directories where the package.json files are located.

runs:
  using: composite
  steps:
    - name: Setup NodeJs Extensions
      shell: pwsh
      run: |
        $LombiqNodeJsExtensions = $(Resolve-Path '${{ github.action_path }}/../../../Lombiq.NodeJs.Extensions').Path
        Write-Output "LOMBIQ_NODEJS_EXTENSIONS=$LombiqNodeJsExtensions"
        "LOMBIQ_NODEJS_EXTENSIONS=$LombiqNodeJsExtensions" >> $Env:GITHUB_ENV

        corepack enable
        corepack prepare pnpm@8.15.9+sha1.aa4bc353b5f59fe1f1df5d802ce049ddf7f3c60e --activate

        cd $LombiqNodeJsExtensions
        pnpm install --prefer-offline --no-frozen-lockfile
        pnpm link --global

    - name: Execute Linting
      shell: pwsh
      run: |
        $project = Get-Content $Env:LOMBIQ_NODEJS_EXTENSIONS/package.json | ConvertFrom-Json -AsHashtable
        $packages = $project['devDependencies'].Keys | ForEach-Object { $version = $project['devDependencies'][$PsItem]; "$PsItem@$version" }

        function Test-NoPath($Paths) { -not (Test-Path -Path $Paths | Where-Object { $PsItem }) }

        function Invoke-NodeJsExtensions($Type) { npm explore nodejs-extensions -- pnpm "lint:$Type" }

        function Install-NodeJsExtensions($Path)
        {
          Set-Location $Path

          if (Test-NoPath -Paths package.json,package.json5,package.yaml) {
            Copy-Item $Env:LOMBIQ_NODEJS_EXTENSIONS/config/consumer/package.project.json package.json
          }

          if (Test-NoPath -Paths .eslintrc,.eslintrc.js) {
            Copy-Item $Env:LOMBIQ_NODEJS_EXTENSIONS/config/consumer/.eslintrc.project.js .eslintrc.js
          }

          if (Test-NoPath -Paths .prettierrc,.prettierrc.js) {
            Copy-Item $Env:LOMBIQ_NODEJS_EXTENSIONS/config/consumer/.prettierrc.project.js .prettierrc.js
          }

          $StyleLintPaths = @(
            '.stylelintrc'
            '.stylelintrc.js'
            '.stylelintrc.mjs'
            '.stylelintrc.cjs'
            '.stylelintrc.yml'
            '.stylelintrc.yaml'
            '.stylelintrc.json'
            'stylelint.config.js'
            'stylelint.config.mjs'
            'stylelint.config.cjs'
          )
          if (Test-NoPath -Paths ) {
            Copy-Item $Env:LOMBIQ_NODEJS_EXTENSIONS/config/consumer/.stylelintrc.project.js .stylelintrc.js
          }

          pnpm link --global nodejs-extensions
          pnpm install @packages --no-frozen-lockfile
        }

        if ('${{ inputs.script-paths }}'.Trim()) {
          Get-Item ${{ inputs.script-paths }} | ForEach-Object {
            Install-NodeJsExtensions -Path $PsItem
            Invoke-NodeJsExtensions -Type scripts
          }
        }

        if ('${{ inputs.style-paths }}'.Trim()) {
          Get-Item ${{ inputs.style-paths }} | ForEach-Object {
            Install-NodeJsExtensions -Path $PsItem
            Invoke-NodeJsExtensions -Type styles
          }
        }

        if ('${{ inputs.style-css-paths }}'.Trim()) {
          Get-Item ${{ inputs.style-css-paths }} | ForEach-Object {
            Install-NodeJsExtensions -Path $PsItem
            Invoke-NodeJsExtensions -Type styles-css
          }
        }
