name: Lint Scripts and Styles

on:
  workflow_call:
    secrets:
      CHECKOUT_TOKEN:
        required: false
        description: >
          The GitHub token to authenticate checkout with. Pass in a GitHub personal access token if authenticated
          submodules are used.

    inputs:
      cancel-workflow-on-failure:
        description: When set to "true", it will cancel the current workflow run with all jobs if this workflow fails.
        type: string
        default: 'true'
      scripts:
        description: |
          Information about the projects where JavaScript linting should occur. Can be in two formats:
          - A comma separated list of relative paths to the project directories. These are the paths where a package.json
            file could be, if desired. If there is no package.json on the provided path, the default one from this
            repository is copied and the default asset subpath (./Assets/Scripts) is assumed. Using this approach, you have
            to copy the assets to their final path (in ./wwwroot) using a different method, for example using the Copy
            task in MSBuild.
          - JSON object where the property names are the relative paths to the project directory where the package.json
            file would be. For each path, a new package.json file is created from the template in this repository and then
            the value of the property is placed into the $.nodejsExtensions path in the project file.
        type: string
        default: ''
      styles-scss:
        description: Information about the projects where SCSS linting should occur. Has the same format as the "scripts" input above.
        type: string
        default: ''
      styles-css:
        description: Information about the projects where CSS linting should occur. Has the same format as the "scripts" input above.
        type: string
        default: ''

jobs:
  lint:
    name: Lint Scripts and Styles
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Run Linter
        uses: Lombiq/NodeJs-Extensions/.github/actions/lint@issue/OCC-314
        with:
          scripts: ${{ inputs.scripts }}
          styles-scss: ${{ inputs.styles-scss }}
          styles-css: ${{ inputs.styles-css }}

      - name: Cancel Workflow on Failure
        if: failure() && inputs.cancel-workflow-on-failure == 'true'
        uses: Lombiq/GitHub-Actions/.github/actions/cancel-workflow@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
