name: Lint Non-Asset Scripts in this Repository

# Runs for PRs opened for any branch, and pushes to the main branch.
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-scripts:
    name: Lint Helper Scripts
    uses: Lombiq/NodeJs-Extensions/.github/workflows/lint.yml@issue/OSOE-954-alt
    with:
      scripts: '
      {
        "Lombiq.NodeJs.Extensions": { "scripts": { "source": "scripts" } }
      }'
  lint-config:
    name: Lint config files
    uses: Lombiq/NodeJs-Extensions/.github/workflows/lint.yml@issue/OSOE-954-alt
    with:
      scripts: '
      {
        "Lombiq.NodeJs.Extensions": { "scripts": { "source": "config" } }
      }'
