name: Lint Script and Style

on:
  workflow_call:
    secrets:
      CHECKOUT_TOKEN:
        required: false
        description: >
          The GitHub token to authenticate checkout with. Pass in a GitHub personal access token if authenticated
          submodules are used.

    inputs:
      cancel-workflow-on-failure:
        description: When set to "true", it will cancel the current workflow run with all jobs if this workflow fails.
        type: string
        default: 'true'
      paths:
        description: Paths to the directories where the package.json files are located.
        type: string
        default: .
      script-paths:
        description: Paths for JavaScript linting to the directories where the package.json files are located.
        type: string
        default: ''
      style-paths:
        description: Paths for Sass linting to the directories where the package.json files are located.
        type: string
        default: ''
      style-css-paths:
        description: Paths for CSS linting to the directories where the package.json files are located.
        type: string
        default: ''

jobs:
  lint:
    name: Lint Script and Style
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Run Linter
        uses: Lombiq/NodeJs-Extensions/.github/actions/lint@issue/OCC-314
        with:
          script-paths: ${{ inputs.script-paths }}
          style-paths: ${{ inputs.style-paths }}
          style-css-paths: ${{ inputs.style-css-paths }}

      - name: Cancel Workflow on Failure
        if: failure() && inputs.cancel-workflow-on-failure == 'true'
        uses: Lombiq/GitHub-Actions/.github/actions/cancel-workflow@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
